version: 0.6.{build}

shallow_clone: true

environment:
  matrix:
    - configuration: Visual Studio 12.0
      platform: x86

    - configuration: Visual Studio 12.0
      platform: x64

    - configuration: Visual Studio 14.0
      platform: x86

    - configuration: Visual Studio 14.0
      platform: x64
      
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x86
      BUILDER: VS
      
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x86
      BUILDER: MSYS2

before_build:
    - call "%ProgramFiles(x86)%\Microsoft %configuration%\VC\vcvarsall.bat" %platform%
    - mkdir build
    - cd build
    - cmake -G "NMake Makefiles" ..

build_script: nmake
